# Generated by Django 3.2.9 on 2021-12-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='zahlart',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Karte', 'Karte')], default='K', max_length=10),
        ),
    ]
