# Generated by Django 3.2.9 on 2021-12-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_alter_receipt_zahlart'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='belegnummer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
