# Generated by Django 3.2.9 on 2021-12-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0003_receipt_belegnummer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='receipt',
        ),
    ]
