# Generated by Django 3.2.9 on 2021-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontaktnummer', models.IntegerField()),
                ('firma', models.CharField(max_length=25)),
                ('ansprechpartner', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=50)),
                ('telefonnummer', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='konto',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=22)),
                ('bic', models.CharField(max_length=10)),
                ('kontostand', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belegnummer', models.IntegerField()),
                ('belegdatum', models.DateField()),
                ('zahlart', models.CharField(choices=[('Bar', 'Bar'), ('Karte', 'Karte')], default='Karte', max_length=10)),
                ('faelligkeit', models.DateField()),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beschreibung', models.CharField(max_length=150)),
                ('art', models.CharField(choices=[('Einnahme', 'Einnahme'), ('Ausgabe', 'Ausgabe')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabe', models.CharField(max_length=50)),
                ('erledigt', models.IntegerField()),
            ],
        ),
    ]
