# Generated by Django 3.2.9 on 2022-01-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
