# Generated by Django 3.2.9 on 2022-01-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_konto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='konto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.konto'),
            preserve_default=False,
        ),
    ]
