# Generated by Django 3.2.9 on 2021-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_receipt_belegnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='zahlart',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Karte', 'Karte')], default='Karte', max_length=10),
        ),
    ]
