# Generated by Django 3.2.9 on 2022-01-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_receipt_konto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konto',
            name='id',
        ),
    ]
