# Generated by Django 3.2.9 on 2021-12-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_receipt_zahlart'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontaktnummer', models.IntegerField()),
                ('firma', models.CharField(max_length=25)),
                ('ansprechpartner', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=50)),
                ('telefonnummer', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
