# Generated by Django 3.2.9 on 2022-01-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AddField(
            model_name='todo',
            name='beschreibung',
            field=models.CharField(default='Programmieren', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='datum',
            field=models.DateField(default='2022-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='faelligkeit',
            field=models.DateField(default='2022-08-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='nummer',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='art',
            field=models.CharField(choices=[('Einnahme', 'Einnahme'), ('Ausgabe', 'Ausgabe')], default='Einnahme', max_length=10),
        ),
    ]
