# Generated by Django 3.2.9 on 2022-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220106_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='aufgabe',
            field=models.CharField(max_length=30),
        ),
    ]
